[tools]
flutter = "3.41.9-stable"
ninja = "1.13.2"

[tasks.install]
description = "Install Dart dependencies."
run = "flutter pub get"

[tasks.fmyt]
description = "Check Dart formatting."
run = "dart format --set-exit-if-changed ."
